version: '3.8'
services:
  db:
    image: postgres:latest
    hostname: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '54321:5432'
    volumes:
      - /var/lib/postgresql/data